#!/usr/bin/env bash

set -e
set -u
set -o pipefail

SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

"$SCRIPTDIR/all-versions" | perl -n -e'/(\d+\.\d+)\./ && print $1 . "\n"' | sort -uV
