#!/usr/bin/env bash

set -e
set -u
set -o pipefail

SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

git ls-remote --tags --refs -q https://github.com/kubernetes/kubectl | awk '{print $2}' | awk -F/ '{ print $3 }' | perl -n -e'/^kubernetes-(\d+\.\d+\.\d+)$/ && print $1 . "\n"' | sort -uV | grep -v -x -F -f "${SCRIPTDIR}/filter-versions"
