#!/usr/bin/env bash

set -e
set -u
set -o pipefail

git ls-remote --tags --refs -q https://github.com/kubernetes/kubectl | awk '{print $2}' | awk -F/ '{ print $3 }' | perl -n -e'/kubernetes-(\d+\.\d+\.\d+)/ && print $1 . "\n"' | sort -u
