name: build

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  IMAGE_NAME: kubectl

jobs:

  build:

    name: build
    runs-on: ubuntu-20.04

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to github container repository
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login https://ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Login to quay.io
        env:
          QUAY_BOT: "+github"
        run: echo "${{ secrets.QUAY_TOKEN }}" | docker login https://quay.io -u "${{ secrets.QUAY_USER }}${QUAY_BOT}" --password-stdin

      - name: Login to docker.io
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login https://index.docker.io/v1/ -u "${{ secrets.DOCKER_USER }}" --password-stdin

      - name: Build all versions
        run: |
          .github/build-all

      - name: Push all versions
        run: |
          .github/push-all ghcr.io/${{ github.repository_owner }}/${IMAGE_NAME} quay.io/${{ secrets.QUAY_USER }}/${IMAGE_NAME} docker.io/${{ secrets.DOCKER_USER }}/${IMAGE_NAME}

      - name: Upload logs
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: logs
          path: |
            build.log
            push.log
