name: build

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: kubectl

jobs:

  build:

    name: build
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        version:
          - "1.18.0"
          - "1.19.0"
          - latest

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build container
        run: |
          docker build . --tag $IMAGE_NAME --build-arg=${{ matrix.version }}

      - name: Login to github container repository
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push latest to github container repository
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          docker tag $IMAGE_NAME $IMAGE_ID:${{ matrix.version }}
          docker push $IMAGE_ID:${{ matrix.version }}
