name: build

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "5 4 * * 0"

env:
  IMAGE_NAME: kubectl

jobs:

  versions:
    runs-on: ubuntu-22.04
    outputs:
      matrix: ${{ steps.eval-matrix.outputs.matrix }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Evaluate build matrix
        id: eval-matrix
        run: |
          matrix=$(.github/build-matrix | LC_ALL=C sed -e 's/[^a-zA-Z0-9,._+@%/-]/\\&/g; 1{$s/^$/""/}; 1!s/^/"/; $!s/$/"/' )
          echo "$matrix"
          echo "::set-output name=matrix::$matrix"

  build:

    runs-on: ubuntu-22.04
    needs: [ "versions" ]

    strategy:
      matrix: ${{ fromJson(needs.versions.outputs.matrix) }}

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to github container repository
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login https://ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Login to quay.io
        env:
          QUAY_BOT: "+github"
        run: echo "${{ secrets.QUAY_TOKEN }}" | docker login https://quay.io -u "${{ secrets.QUAY_USER }}${QUAY_BOT}" --password-stdin

      - name: Login to docker.io
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login https://index.docker.io/v1/ -u "${{ secrets.DOCKER_USER }}" --password-stdin

      - name: Build micro versions of ${{ matrix.version }}
        env:
          VERSION: ${{ matrix.version }}
          LATEST: ${{ matrix.latest }}
        run: |
          .github/build-minor ${{ matrix.version }} ${{ matrix.latest }}

      - name: Push all versions
        env:
          VERSION: ${{ matrix.version }}
          LATEST: ${{ matrix.latest }}
        run: |
          .github/push-minor ghcr.io/${{ github.repository_owner }}/${IMAGE_NAME} quay.io/${{ secrets.QUAY_USER }}/${IMAGE_NAME} docker.io/${{ secrets.DOCKER_USER }}/${IMAGE_NAME}

      - name: Upload logs
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: logs-${{ matrix.version }}
          path: |
            build.log
            push.log
